In [1]:
# Sample Decision Tree Classifier
from sklearn import datasets
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier

In [2]:
# load the iris datasets
dataset = datasets.load_iris()

In [3]:
type(dataset)

sklearn.datasets.base.Bunch

In [5]:
dataset.items()

[('target_names', array(['setosa', 'versicolor', 'virginica'], 
        dtype='|S10')), ('data', array([[ 5.1,  3.5,  1.4,  0.2],
         [ 4.9,  3. ,  1.4,  0.2],
         [ 4.7,  3.2,  1.3,  0.2],
         [ 4.6,  3.1,  1.5,  0.2],
         [ 5. ,  3.6,  1.4,  0.2],
         [ 5.4,  3.9,  1.7,  0.4],
         [ 4.6,  3.4,  1.4,  0.3],
         [ 5. ,  3.4,  1.5,  0.2],
         [ 4.4,  2.9,  1.4,  0.2],
         [ 4.9,  3.1,  1.5,  0.1],
         [ 5.4,  3.7,  1.5,  0.2],
         [ 4.8,  3.4,  1.6,  0.2],
         [ 4.8,  3. ,  1.4,  0.1],
         [ 4.3,  3. ,  1.1,  0.1],
         [ 5.8,  4. ,  1.2,  0.2],
         [ 5.7,  4.4,  1.5,  0.4],
         [ 5.4,  3.9,  1.3,  0.4],
         [ 5.1,  3.5,  1.4,  0.3],
         [ 5.7,  3.8,  1.7,  0.3],
         [ 5.1,  3.8,  1.5,  0.3],
         [ 5.4,  3.4,  1.7,  0.2],
         [ 5.1,  3.7,  1.5,  0.4],
         [ 4.6,  3.6,  1. ,  0.2],
         [ 5.1,  3.3,  1.7,  0.5],
         [ 4.8,  3.4,  1.9,  0.2],
         [ 5. ,  3. ,  1.6,  0

In [6]:
dataset.data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [7]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
# fit a CART model to the data
model = DecisionTreeClassifier()
model.fit(dataset.data, dataset.target)
print(model)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')


In [9]:
# make predictions
expected = dataset.target
predicted = model.predict(dataset.data)

In [10]:
type(expected), type(predicted)

(numpy.ndarray, numpy.ndarray)

In [11]:
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       1.00      1.00      1.00        50
          2       1.00      1.00      1.00        50

avg / total       1.00      1.00      1.00       150



In [12]:
print(metrics.confusion_matrix(expected, predicted))

[[50  0  0]
 [ 0 50  0]
 [ 0  0 50]]


In [13]:
#now try the same in my own code
import pandas as pd

In [16]:
iris_df = pd.read_csv('/home/shenbaga/data-files/iris.data', \
                      names = ['sepal_length','sepal_width','petal_length','petal_width','class'])

In [17]:
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [18]:
train = iris_df.sample(frac=0.8,random_state=200)
test = iris_df.drop(train.index)

In [20]:
len(iris_df), len(train), len(test)

(150, 120, 30)

In [41]:
train[['class']].head()

class
84   Iris-versicolor
122   Iris-virginica
28       Iris-setosa
24       Iris-setosa
75   Iris-versicolor

In [42]:
train[['sepal_length','sepal_width','petal_length','petal_width']].head()

sepal_length  sepal_width  petal_length  petal_width
84            5.4          3.0           4.5          1.5
122           7.7          2.8           6.7          2.0
28            5.2          3.4           1.4          0.2
24            4.8          3.4           1.9          0.2
75            6.6          3.0           4.4          1.4

In [43]:
# fit a CART model to the data
model2 = DecisionTreeClassifier()

In [44]:
#model2.fit(dataset.data, dataset.target)
model2.fit(train[['sepal_length','sepal_width','petal_length','petal_width']],train[['class']])
print(model)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')


In [46]:
# make predictions
expected = train[['class']]
predicted = model.predict(train[['sepal_length','sepal_width','petal_length','petal_width']])

In [48]:
expected

class
84   Iris-versicolor
122   Iris-virginica
28       Iris-setosa
24       Iris-setosa
75   Iris-versicolor
109   Iris-virginica
81   Iris-versicolor
98   Iris-versicolor
80   Iris-versicolor
100   Iris-virginica
124   Iris-virginica
2        Iris-setosa
34       Iris-setosa
44       Iris-setosa
128   Iris-virginica
13       Iris-setosa
93   Iris-versicolor
41       Iris-setosa
63   Iris-versicolor
137   Iris-virginica
19       Iris-setosa
60   Iris-versicolor
126   Iris-virginica
11       Iris-setosa
47       Iris-setosa
18       Iris-setosa
96   Iris-versicolor
107   Iris-virginica
141   Iris-virginica
53   Iris-versicolor
..               ...
27       Iris-setosa
82   Iris-versicolor
6        Iris-setosa
102   Iris-virginica
62   Iris-versicolor
146   Iris-virginica
58   Iris-versicolor
144   Iris-virginica
78   Iris-versicolor
123   Iris-virginica
114   Iris-virginica
90   Iris-versicolor
52   Iris-versicolor
111   Iris-virginica
72   Iris-versicolor
33       Iris-setosa
110   Iris-virginica
136   Iris-virginica
95   Iris-versicolor
55   Iris-versicolor
3        Iris-setosa
0        Iris-setosa
130   Iris-virginica
20       Iris-setosa
61   Iris-versicolor
117   Iris-virginica
59   Iris-versicolor
45       Iris-setosa
32       Iris-setosa
31       Iris-setosa

[120 rows x 1 columns]

In [49]:
predicted

array([1, 2, 0, 0, 1, 2, 1, 1, 1, 2, 2, 0, 0, 0, 2, 0, 1, 0, 1, 2, 0, 1, 2,
       0, 0, 0, 1, 2, 2, 1, 0, 1, 1, 0, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2,
       2, 0, 2, 1, 2, 1, 1, 1, 2, 0, 1, 1, 1, 2, 0, 0, 2, 0, 0, 2, 1, 0, 0,
       2, 0, 0, 2, 2, 1, 1, 2, 0, 0, 2, 1, 0, 2, 2, 0, 0, 1, 2, 1, 2, 0, 1,
       0, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 0, 2, 2, 1, 1, 0, 0, 2, 0, 1,
       2, 1, 0, 0, 0])

In [47]:
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))

ValueError: Mix of label input types (string and number)

In [54]:
# Select the first 2 columns
#df.iloc[:,:2]
iris_df.iloc[:, :2].head()

sepal_length  sepal_width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2
3           4.6          3.1
4           5.0          3.6

In [58]:
iris_df.iloc[:, :-1].head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [64]:
iris_df.iloc[:, [4]].head()

class
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

In [66]:
df_mod = iris_df.copy()
targets = df_mod['class'].unique()
map_to_int = {name: n for n, name in enumerate(targets)}
map_to_int

{'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}

In [67]:
def encode_target(df, target_column):
    """Add column to df with integers for the target.

    Args
    ----
    df -- pandas DataFrame.
    target_column -- column to map to int, producing
                     new Target column.

    Returns
    -------
    df_mod -- modified DataFrame.
    targets -- list of target names.
    """
    df_mod = df.copy()
    targets = df_mod[target_column].unique()
    map_to_int = {name: n for n, name in enumerate(targets)}
    df_mod["Target"] = df_mod[target_column].replace(map_to_int)

    return (df_mod, targets)

In [68]:
df2, targets = encode_target(iris_df, "class")
df2.head()

sepal_length  sepal_width  petal_length  petal_width        class  Target
0           5.1          3.5           1.4          0.2  Iris-setosa       0
1           4.9          3.0           1.4          0.2  Iris-setosa       0
2           4.7          3.2           1.3          0.2  Iris-setosa       0
3           4.6          3.1           1.5          0.2  Iris-setosa       0
4           5.0          3.6           1.4          0.2  Iris-setosa       0

In [69]:
features = ['sepal_length','sepal_width','petal_length','petal_width']

In [70]:
y = df2["Target"]
X = df2[features]
dt = DecisionTreeClassifier(min_samples_split=20, random_state=99)
dt.fit(X, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=20, min_weight_fraction_leaf=0.0,
            presort=False, random_state=99, splitter='best')

In [74]:
from sklearn.tree import export_graphviz
#import graphviz

In [75]:
def visualize_tree(tree, feature_names):
    """Create tree png using graphviz.

    Args
    ----
    tree -- scikit-learn DecsisionTree.
    feature_names -- list of feature names.
    """
    with open("dt.dot", 'w') as f:
        export_graphviz(tree, out_file=f,
                        feature_names=feature_names)

    command = ["dot", "-Tpng", "dt.dot", "-o", "dt.png"]
    try:
        subprocess.check_call(command)
    except:
        exit("Could not run dot, ie graphviz, to "
             "produce visualization")

In [77]:
visualize_tree(dt, features)

In [80]:
import graphviz

ImportError: No module named graphviz

In [78]:
export_graphviz(dt, out_file="mytree.dot")
with open("mytree.dot") as f:
    dot_graph = f.read()
graphviz.Source(dot_graph)

NameError: name 'graphviz' is not defined

In [81]:
from IPython.display import Image

In [93]:
from sklearn import tree
dot_data = tree.export_graphviz(dt, \
                                feature_names=features, \
                                class_names=['0','1','2'], \
                                filled=True, rounded=True, \
                                special_characters=True)

In [87]:
import pydotplus

In [94]:
graph = pydotplus.graph_from_dot_data(dot_data) 
Image(graph.create_png())

AttributeError: 'NoneType' object has no attribute 'startswith'

In [92]:
dot_data = tree.export_graphviz(dt)
graph = pydotplus.graph_from_dot_data(dot_data) 
graph.write_pdf("iris.pdf") 

AttributeError: 'NoneType' object has no attribute 'startswith'

In [95]:
dot_data = tree.export_graphviz(dt)
graph = pydotplus.graphviz.graph_from_dot_data(dot_data)

AttributeError: 'NoneType' object has no attribute 'startswith'

In [96]:
from sklearn.datasets import load_iris
from sklearn import tree
iris = load_iris()
clf = tree.DecisionTreeClassifier()
clf = clf.fit(iris.data, iris.target)

In [97]:
clf

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [123]:
with open("iris.dot", 'w') as f:
    f = tree.export_graphviz(clf, feature_names=features, class_names=['0','1','2'], out_file=f)

In [124]:
import subprocess
subprocess.call(['dot', '-Tpdf', 'iris.dot', '-o' 'tree3.pdf'])

0

In [99]:
f

In [100]:
type(f)

NoneType

In [102]:
type(iris.dot)

AttributeError: dot

In [103]:
dot -Tpdf iris.dot -o iris.pdf

SyntaxError: invalid syntax (<ipython-input-103-f3425d4a118a>, line 1)

In [104]:
import os
os.unlink('iris.dot')

In [106]:
import pydotplus 
dot_data = tree.export_graphviz(clf)

In [107]:
graph = pydotplus.graph_from_dot_data(dot_data) 
graph.write_pdf("iris.pdf") 

AttributeError: 'NoneType' object has no attribute 'startswith'

In [111]:
import subprocess
subprocess.call(['dot', '-Tpdf', 'iris.dot', '-o' 'tree.pdf'])

0

In [112]:
from sklearn.externals.six import StringIO
import pydot 

In [114]:
dot_data = StringIO() 
tree.export_graphviz(clf, out_file=dot_data) 
graph = pydot.graph_from_dot_data(dot_data.getvalue())

In [116]:
graph, type(graph)

([<pydot.Dot at 0x7f6630b41490>], list)

In [117]:
graph.write_pdf("graph.pdf") 

AttributeError: 'list' object has no attribute 'write_pdf'

In [119]:
type(iris.dot)

AttributeError: dot

In [121]:
os.getcwd()

'/home/shenbaga/Ipython Notebooks'

In [122]:
import subprocess
subprocess.call(['dot', '-Tpdf', 'iris.dot', '-o' 'tree2.pdf'])

0

In [127]:
#a method to get the tree as pdf

from sklearn.datasets import load_iris
#from sklearn import tree
#iris = load_iris()
clf = tree.DecisionTreeClassifier()
clf = clf.fit(iris.data, iris.target)

with open("iris.dot", 'w') as f:
    f = tree.export_graphviz(clf, feature_names=features, out_file=f,class_names=iris.target_names)

import subprocess
subprocess.call(['dot', '-Tpdf', 'iris.dot', '-o' 'tree5.pdf'])

0

In [128]:
type(iris.target_names)

numpy.ndarray

In [129]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='|S10')

In [131]:
test.head()

sepal_length  sepal_width  petal_length  petal_width        class
1            4.9          3.0           1.4          0.2  Iris-setosa
7            5.0          3.4           1.5          0.2  Iris-setosa
14           5.8          4.0           1.2          0.2  Iris-setosa
16           5.4          3.9           1.3          0.4  Iris-setosa
23           5.1          3.3           1.7          0.5  Iris-setosa

In [132]:
len(test)

30

In [133]:
df2.head()

sepal_length  sepal_width  petal_length  petal_width        class  Target
0           5.1          3.5           1.4          0.2  Iris-setosa       0
1           4.9          3.0           1.4          0.2  Iris-setosa       0
2           4.7          3.2           1.3          0.2  Iris-setosa       0
3           4.6          3.1           1.5          0.2  Iris-setosa       0
4           5.0          3.6           1.4          0.2  Iris-setosa       0

In [134]:
train = df2.sample(frac=0.8,random_state=200)
test = df2.drop(train.index)

In [135]:
features

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [136]:
y = train["Target"]
X = train[features]
dt_2 = DecisionTreeClassifier(min_samples_split=20, random_state=99)
dt_2.fit(X, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=20, min_weight_fraction_leaf=0.0,
            presort=False, random_state=99, splitter='best')

In [139]:
predicted = dt_2.predict(test[features])

In [140]:
actual = test["Target"]

In [141]:
actual

1      0
7      0
14     0
16     0
23     0
26     0
35     0
42     0
51     1
54     1
56     1
68     1
70     1
76     1
77     1
79     1
85     1
89     1
105    2
106    2
115    2
116    2
120    2
129    2
134    2
138    2
139    2
142    2
145    2
147    2
Name: Target, dtype: int64

In [142]:
# summarize the fit of the model
print(metrics.classification_report(actual, predicted))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         8
          1       0.89      0.80      0.84        10
          2       0.85      0.92      0.88        12

avg / total       0.90      0.90      0.90        30



In [143]:
print(metrics.confusion_matrix(actual, predicted))

[[ 8  0  0]
 [ 0  8  2]
 [ 0  1 11]]


In [144]:
#cross validation

In [145]:
from sklearn.cross_validation import  cross_val_score

In [146]:
y = train["Target"]
X = train[features]

In [149]:
print("-- 10-fold cross-validation "
      "[using setup from previous post]")
dt_old = DecisionTreeClassifier(min_samples_split=20, random_state=99)
dt_old.fit(X, y)
scores = cross_val_score(dt_old, X, y, cv=10)
print scores.mean()
print scores.std()
#print("mean: {:.3f} (std: {:.3f})".format(scores.mean(),scores.std()),end="\n\n" )

-- 10-fold cross-validation [using setup from previous post]
0.965151515152
0.0589937040422


In [1]:
def run_gridsearch(X, y, clf, param_grid, cv=5):
    """Run a grid search for best Decision Tree parameters.

    Args
    ----
    X -- features
    y -- targets (classes)
    cf -- scikit-learn Decision Tree
    param_grid -- [dict] parameter settings to test
    cv -- fold of cross-validation, default 5

    Returns
    -------
    top_params -- [dict] from report()
    """
    grid_search = GridSearchCV(clf,
                               param_grid=param_grid,
                               cv=cv)
    start = time()
    grid_search.fit(X, y)

    print(("\nGridSearchCV took {:.2f} "
           "seconds for {:d} candidate "
           "parameter settings.").format(time() - start,
                len(grid_search.grid_scores_)))

    top_params = report(grid_search.grid_scores_, 3)
    return  top_params